os: Visual Studio 2017

environment:
  matrix:
    - arch: x86
      compiler: msvc2015
    - arch: x64
      compiler: msvc2017

platform:
  - x64

install:
  # Download ninja
  - cmd: mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://www.dropbox.com/s/cyghxjrvgplu7sy/ninja.exe?dl=1', 'C:\ninja-build\ninja.exe')
  # Set paths to dependencies (based on architecture)
  - cmd: if %arch%==x86 (set PYTHON_ROOT=C:\python37) else (set PYTHON_ROOT=C:\python37-x64)
  - cmd: if %arch%==x86 (set QT_ROOT=C:\Qt\5.11\%compiler%) else (set QT_ROOT=C:\Qt\5.11\%compiler%_64)
  # Print out dependency paths
  - cmd: echo Using Python at %PYTHON_ROOT%
  - cmd: echo Using Qt at %QT_ROOT%
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%QT_ROOT%\bin;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson
  - cmd: if "%APPVEYOR_PROJECT_NAME%"=="razer_test meson nightly" (pip install git+https://github.com/mesonbuild/meson.git) else (pip install meson==0.48.2)
  # Set up the build environment
  - cmd: if %compiler%==msvc2015 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch% )
  - cmd: if %compiler%==msvc2017 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja -Dbuild_bringup_util=true -Dbuild_tests=true builddir
  - cmd: ninja -C builddir

test_script:
  - cmd: ninja -C builddir test

after_build:
  # Zip build binaries and dependencies
  - cmd: 7z a razer_test_%compiler%_%arch%.zip %APPVEYOR_BUILD_FOLDER%\builddir\razer_test.exe %APPVEYOR_BUILD_FOLDER%\builddir\razer_test_bringup_util.exe %APPVEYOR_BUILD_FOLDER%\builddir\subprojects\hidapi\hidapi.dll %QT_ROOT%\bin\Qt5Cored.dll %QT_ROOT%\bin\Qt5DBusd.dll

artifacts:
  - path: razer_test*.zip

notifications:
  - provider: Slack
    incoming_webhook: https://webhooks.t2bot.io/api/v1/matrix/hook/gEsoLVFFgp4PURc6iR8IhdQAFhOslmSzfy35y4DEtGL0a5QKIXPIGKUFaJsWkJ7F
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
